#!/bin/bash
# this script is ontouch git push script
# how to use: 
# ~$ sh gitt "write your commit as you want"
rm -f 0.*.txt
rm -f 0.*.txt.xml
git add *
git push 
git commit -m "$1"
git push origin master
exit
